In [1]:
import numpy as np

In [2]:
def one_hot_encode_words(text):
    """One-hot encodes words in a given text."""

    words = text.lower().split()  # Tokenize and lowercase
    unique_words = sorted(list(set(words)))
    num_words = len(unique_words)

    word_to_index = {word: i for i, word in enumerate(unique_words)}
    encoded_text = np.zeros((len(words), num_words), dtype=int)

    for i, word in enumerate(words):
        encoded_text[i, word_to_index[word]] = 1

    return encoded_text, unique_words, word_to_index

In [3]:
def one_hot_encode_characters(text):
    """One-hot encodes characters in a given text."""

    text = text.lower() # lowercase
    unique_chars = sorted(list(set(text)))
    num_chars = len(unique_chars)

    char_to_index = {char: i for i, char in enumerate(unique_chars)}
    encoded_text = np.zeros((len(text), num_chars), dtype=int)

    for i, char in enumerate(text):
        encoded_text[i, char_to_index[char]] = 1

    return encoded_text, unique_chars, char_to_index


In [4]:
# Example usage (words):
text_words = "This is a simple example. This example is simple."
encoded_words, unique_words, word_to_index = one_hot_encode_words(text_words)

print("Word-level one-hot encoding:")
print("Encoded text:\n", encoded_words)
print("\nUnique words:", unique_words)
print("\nWord to index mapping:", word_to_index)

# Example usage (characters):
text_chars = "Hello, world!"
encoded_chars, unique_chars, char_to_index = one_hot_encode_characters(text_chars)

print("\nCharacter-level one-hot encoding:")
print("Encoded text:\n", encoded_chars)
print("\nUnique characters:", unique_chars)
print("\nCharacter to index mapping:", char_to_index)

Word-level one-hot encoding:
Encoded text:
 [[0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0]]

Unique words: ['a', 'example', 'example.', 'is', 'simple', 'simple.', 'this']

Word to index mapping: {'a': 0, 'example': 1, 'example.': 2, 'is': 3, 'simple': 4, 'simple.': 5, 'this': 6}

Character-level one-hot encoding:
Encoded text:
 [[0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]]

Unique characters: [' ', '!', ',', 'd', 'e', 'h', 'l', 'o', 'r', 'w']

Character to index mapping: {' ': 0, '!': 1, ',': 2, 'd': 3, 'e': 4, 'h': 5, 'l': 6, 'o': 7, 'r': 8, 'w': 9}
